### ISSUE TITLE
Update NodeJS and libraries to latest versions

### ISSUE THREAD

**Issue by mgvarley** [urbanriskmap/cognicity-rem-server#10]
Node version is currently on 4.2.1 and latest recommended version is 6.9.1 (see https://nodejs.org/en/).  Would be a good opportunity to move to latest stable Node and update npm dependencies accordingly.  Are you OK with this @matthewberryman ?

**Comment by matthewberryman** [comment]
I already updated npm dependencies back in https://github.com/urbanriskmap/cognicity-rem-server/commit/6d6cf84b391647067e65ffdba7f63edbe2824158 and https://github.com/urbanriskmap/cognicity-rem-web/commit/be7ee844f87c1be254aaa73078d63779e710d96d and it's been running fine since then on node v6 (v6.2.2 on EB prod and v.6.7.0 on dev). The README.md is correct (4.2.1 *or later*) however the packages.json entry needs to read ">=" (for humans, it's not read by software as cognicity-rem-server isn't a node module), and I will update .travis.yml to reflect the node version used on prod.

**Comment by matthewberryman** [comment]
We should also use ES6 js in the server (but not in the web pages submodule), I would argue, not just for this but for cognicity-reports* and cognicity-server. @mgvarley @talltom thoughts?

**Comment by mgvarley** [comment]
Hi Matthew - I would be very happy to use ES6 on server - I am using it on the client side too on my own projects using webpack / babel but that is probably a step too far at this stage.  I will avoid any ES7 as a lot of features still appear to be under debate
